train:
  _target_: src.datasets.AVSSDataset
  audio_dir: ./data/datasets/dla_dataset/audio/val
  mouths_dir: ./data/datasets/dla_dataset/mouths
  limit : 2
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.AVSSDataset
  audio_dir: ./data/datasets/dla_dataset/audio/val
  mouths_dir: ./data/datasets/dla_dataset/mouths
  limit : 2
  instance_transforms: ${transforms.instance_transforms.inference}
