train:
  _target_: src.datasets.AVSSDataset
  audio_dir: ./data/datasets/dla_dataset/audio/train_all
  mouths_dir: ./data/datasets/dla_dataset/mouths
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.AVSSDataset
  audio_dir: ./data/datasets/dla_dataset/audio/val_all
  mouths_dir: ./data/datasets/dla_dataset/mouths
  instance_transforms: ${transforms.instance_transforms.inference}
