train: []
inference:
  - _target_: src.metrics.PESQ
    name: "PESQ"
    fs: 16000
    mode: "wb"
  - _target_: src.metrics.SDRi
    name: "SDRi"
  - _target_: src.metrics.SI_SNRi
    name: "SI_SNRi"
  - _target_: src.metrics.STOI
    name: "STOI"
    fs: 16000
