train: []
inference:
  - _target_: src.metrics.PESQ
    name: "PESQ"
  - _target_: src.metrics.SDRi
    name: "SDRi"
  - _target_: src.metrics.SI_SNRi
    name: "SI_SNRi"
  - _target_: src.metrics.STOI
    name: "STOI"
