train:
  source1_mouth:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: src.transforms.Scale
        factor: ${eval:'1.0 / 255.0'}
  source2_mouth:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: src.transforms.Scale
        factor: ${eval:'1.0 / 255.0'}
inference:
  source1_mouth:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: src.transforms.Scale
        factor: ${eval:'1.0 / 255.0'}
  source2_mouth:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: src.transforms.Scale
        factor: ${eval:'1.0 / 255.0'}
