train:
  source1_mouth:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: src.transforms.Scale
        factor: 0.00392156862745
  source2_mouth:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: src.transforms.Scale
        factor: 0.00392156862745
inference:
  source1_mouth:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: src.transforms.Scale
        factor: 0.00392156862745
  source2_mouth:
    _target_: torch.nn.Sequential
    _args_:
      - _target_: src.transforms.Scale
        factor: 0.00392156862745
