_target_: src.model.RTFSNet
hidden_dim: 256
processing_dim: 32
rtfs_blocks_num: 4
video_encoder_dim: 512
rnn_layers: 1
rnn_hidden_dim: 32
vp_compression_blocks: 4
ap_compression_blocks: 2
compression_blocks: 0
n_heads: 4
one_pass: False
